


FIELD = 0
TYPE = 1
NULL = 2
KEY = 3
DEFAULT = 4
EXTRA = 5

CONSTRAINT_CATALOG = 0
CONSTRAINT_SCHEMA = 1
CONSTRAINT_NAME = 2
UNIQUE_CONSTRAINT_CATALOG = 3
UNIQUE_CONSTRAINT_SCHEMA = 4
UNIQUE_CONSTRAINT_NAME = 5
MATCH_OPTION = 6
UPDATE_RULE = 7
DELETE_RULE = 8
TABLE_NAME = 9
REFERENCED_TABLE_NAME = 10

# Delta Comparisons
COMPARE_KEYS = true
COMPARE_KEY_COUNT = false
COMPARE_MUL_KEY = false
COMPARE_UNI_KEY = true
COMPARE_PRI_KEY = true

COMPARE_CONSTRAINTS = true
